[project]
name = "marimo-gh-pages-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bssunfold>=0.1.2",
    "marimo>=0.19.2",
    "numpy>=2.4.1",
    "pandas==2.2.3",
    "plotly>=6.5.1",
]
